config/routes.rb
Rails.application.routes.draw do
  resources :trips do
    member do
      get 'test'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id          :bigint(8)        not null, primary key
#  name        :string
#  origin      :decimal(8, 6)    default([]), is an Array
#  pick_up     :decimal(8, 6)    default([]), is an Array
#  drop_off    :decimal(8, 6)    default([]), is an Array
#  destination :decimal(8, 6)    default([]), is an Array
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Trip < ApplicationRecord


  def self.berlin
    [{"lat": 52.520008 ,"lng": 13.404954}].to_json

  end

  def marker_for(latlong)
    [{"lat": latlong[0] ,"lng": latlong[1]}].to_json

  end


  def origin_marker
    marker_for(origin)
  end


  # def markers
  #   {"lat": lat ,"lng": long}
  #
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  def test
    payload = {
    	"lat": 52.546628,
    	"lon": 13.424536,
    	"time": 1562019845
    }.to_json
    url = '145.20.18.202:505'
    RestClient.post(url, payload, headers={})

  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :origin, :pick_up, :drop_off, :destination)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Parking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    script src="//maps.google.com/maps/api/js?key=AIzaSyDVqHK7fjn-to95Gyzq82WqG2HsNwYh9DE" type="text/javascript"
    script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" type="text/javascript"
    script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'

    = javascript_include_tag 'application'

  body
    = yield

app/views/layouts/partials/_map.slim
/ #results data-locations=markers data-circles=local_assigns[:circles]
#results data-locations=markers data-circles=local_assigns[:circles]
.map_holder.medium
  #map

app/views/trips/_form.html.slim
= form_for @trip do |f|
  - if @trip.errors.any?
    #error_explanation
      h2 = "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
      ul
        - @trip.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :origin
    = f.text_field :origin
  .field
    = f.label :pick_up
    = f.text_field :pick_up
  .field
    = f.label :drop_off
    = f.text_field :drop_off
  .field
    = f.label :destination
    = f.text_field :destination
  .actions = f.submit

app/views/trips/_form_step_1.html.slim
= render "layouts/partials/map", markers: Trip.berlin


.row
  .col-12.no-gutters
    = form_for @trip do |f|
      - if @trip.errors.any?
        #error_explanation
          h2 = "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
          ul
            - @trip.errors.full_messages.each do |message|
              li = message


      .route_input.row.no-gutters
        .icons.col-3
           #gmaps-error = "KJLKJDLKSJDL"

        .col-9
          .field
            = f.text_field :origin_address, id: 'gmaps-input-address', placeholder: 'Start typing a place...'
            = f.label :origin_address, 'Origin'


          .field
            = f.text_field :destination_address
            = f.label :destination_address, 'Destination'
          .actions = f.submit

app/views/trips/edit.html.slim
h1 Editing trip

== render 'form'

=> link_to 'Show', @trip
'|
=< link_to 'Back', trips_path

app/views/trips/index.html.slim
h1 Listing trips

table
  thead
    tr
      th Name
      th Origin
      th Pick up
      th Drop off
      th Destination
      th
      th
      th

  tbody
    - @trips.each do |trip|
      tr
        td = trip.name
        td = trip.origin
        td = trip.pick_up
        td = trip.drop_off
        td = trip.destination
        td = link_to 'Show', trip
        td = link_to 'Edit', edit_trip_path(trip)
        td = link_to 'Destroy', trip, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Trip', new_trip_path

app/views/trips/new.html.slim
/ h1 New trip
/
.container
  == render 'form_step_1'

  / = link_to 'Back', trips_path

app/views/trips/show.html.slim
p#notice = notice

= render "layouts/partials/map", markers: @trip.origin_marker

p
  strong Name:
  = @trip.name
p
  strong Origin:
  = @trip.origin.map(&:to_f)
p
  strong Pick up:
  = @trip.pick_up.map(&:to_f)
p
  strong Drop off:
  = @trip.drop_off.map(&:to_f)
p
  strong Destination:
  = @trip.destination.map(&:to_f)

=> link_to 'Edit', edit_trip_path(@trip)
'|
=< link_to 'Back', trips_path